spring:
  datasource:
    url: jdbc:mysql://localhost:3306/social_network_db?serverTimezone=UTC
    username: springstudent
    password: springstudent

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
jwt:
  token:
    secret: secret
    #Expiration in seconds
    expiration: 10000