spring:
  datasource:
    url: jdbc:mysql://localhost:3306/social_network_database?serverTimezone=UTC
    username: springstudent
    password: springstudent

  jpa:
    hibernate:
      ddl-auto: create-drop
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId: 1100724033470323
            clientSecret: 60667a83ae3bb4a3124bd58e170194b3